### ISSUE TITLE
Benchmarking scala with `currentTimeMillis` is brittle

### ISSUE THREAD

**Issue by gabro** [andreaferretti/levenshtein#2]
Micro-benchmarking on the JVM without an ad-hoc tool is potentially meaningless, due to JIT compilation and JVM optimizations.

Consider using https://github.com/ktoso/sbt-jmh for accurate results.

Also, the nim implementation may suffer of this too, but I don't know enough to tell whether it's an issue or not.

**Comment by andreaferretti** [comment]
Yeah, I kind of know this. But we are talking about benchmarks in the order of the tens of seconds, the effects for which jmh is needed are on a much much finer scale
